services:
  app:
    build:
      context: ./
      dockerfile: ./.devcontainer/remote.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /home/node/workspace
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/node/.gitconfig
      - type: bind
        source: ${HOME}/.local/share/mkcert
        target: /home/node/.local/share/mkcert
    ports:
      - "3000:3000"
    restart: always
