version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./.devcontainer/remote.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /workspace
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/node/.gitconfig
    restart: always
