name: Deploy
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: |
          curl -X GET "https://www.google.com/ping?sitemap=https://sogo.dev/sitemap.xml"
